"""add ingredient, recipe_ingredient, recipe

Revision ID: 86c491d2f6e3
Revises: cc4b883f3909
Create Date: 2022-07-30 15:31:54.914927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c491d2f6e3'
down_revision = 'cc4b883f3909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
