"""fixed relationship cols

Revision ID: b138695408ee
Revises: 86c491d2f6e3
Create Date: 2022-07-31 15:18:32.909329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b138695408ee'
down_revision = '86c491d2f6e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
